#
# Test-job template
#

.ensembl_test_template:
  image: dockerhub.ebi.ac.uk/ensembl-infrastructure/ensembl-ci-docker-images:${PERL_VERSION}

  variables:
    USER: "gitlabci"
    ENSDIR: $CI_PROJECT_DIR/..

  before_script:
    - apt-get update
    - apt-get install -y build-essential cpanminus git
    - cd $ENSDIR
    - git clone --branch=main --depth=1 https://github.com/Ensembl/ensembl.git
    - git clone --branch=main --depth=1 https://github.com/Ensembl/ensembl-test.git
    - cd $CI_PROJECT_DIR
    - cpanm -v --installdeps --notest .
    - perl Makefile.PL
    - make

#
# Test jobs
#

test:perl5.26:
  stage: test
  extends: .ensembl_test_template
  variables:
    PERL_VERSION: "5.26"
    COVERALLS: "false"
  script:
    - ./travisci/harness.sh

test:perl5.30:
  stage: test
  extends: .ensembl_test_template
  variables:
    PERL_VERSION: "5.30"
    COVERALLS: "false"
  script:
    - ./travisci/harness.sh
